import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../../../styles/Layout.module.css";
const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>HomeWork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <ul className={styles.toolBar_menu}>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/components/toolbar/blog">Blog</Link>
            </li>
            <li>
              <Link href="/components/toolbar/about">About</Link>
            </li>
            <li>
              <Link href="/components/toolbar/login">Login</Link>
            </li>
          </ul>
        </nav>
        <div className={styles.main}>
          <h1>{children}</h1>
        </div>
      </main>
    </div>
  );
};

export default Layout;
