import React from "react";
import Head from "next/head";
import styles from "../../../styles/LayoutWeather.module.css";
const LayoutWeather = ({ children }) => {
  return (
    <div className="d-grid">
      <Head>
        <title>Thời tiết Việt Nam</title>
        <link rel="icon" href="/sun-regular.svg" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className="row">
        <div className={styles.banner_1}>asd</div>
      </header>
      <main className={`row bg-light text-capitalize ${styles.main}`}>
        {children}
      </main>
    </div>
  );
};

export default LayoutWeather;
